export interface FinanceApiRoute {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH';
  path: string;
  purpose: string;
}

export const financeApiRoutes: FinanceApiRoute[] = [
  { method: 'POST', path: '/api/finance/tasks/enqueue', purpose: 'enqueue finance task' },
  { method: 'GET', path: '/api/finance/tasks', purpose: 'list tasks' },
  { method: 'GET', path: '/api/finance/tasks/:id', purpose: 'task detail' },
  { method: 'POST', path: '/api/finance/tasks/:id/retry', purpose: 'retry failed task' },
  { method: 'POST', path: '/api/finance/tasks/:id/cancel', purpose: 'cancel pending task' },
  { method: 'POST', path: '/api/finance/ingest/source-documents', purpose: 'source document ingest' },
  { method: 'POST', path: '/api/finance/ingest/outcomes', purpose: 'outcome ingest + review auto-enqueue' },
  { method: 'POST', path: '/api/finance/reviews/:id/correct', purpose: 'manual review correction ingest' },
  { method: 'GET', path: '/api/finance/run-center/summary', purpose: 'run center summary' },
  { method: 'GET', path: '/api/finance/portfolios', purpose: 'list portfolios + detail' },
  { method: 'POST', path: '/api/finance/portfolios', purpose: 'create or update portfolio' },
  { method: 'GET', path: '/api/finance/holdings', purpose: 'list holdings by portfolio' },
  { method: 'POST', path: '/api/finance/holdings', purpose: 'create or update holding' },
  { method: 'GET', path: '/api/finance/watchlist', purpose: 'list watchlist items' },
  { method: 'POST', path: '/api/finance/watchlist', purpose: 'create or update watchlist item' },
  { method: 'GET', path: '/api/finance/reports', purpose: 'list report artifacts' },
  { method: 'POST', path: '/api/finance/reports', purpose: 'create report artifact' },
  { method: 'GET', path: '/api/finance/predictions', purpose: 'list predictions' },
  { method: 'POST', path: '/api/finance/predictions', purpose: 'extract predictions from artifact' },
  { method: 'GET', path: '/api/finance/reviews', purpose: 'list reviews' },
  { method: 'GET', path: '/api/finance/errors/*', purpose: 'list error patterns' },
  { method: 'GET', path: '/api/finance/candidates/*', purpose: 'list candidate proposals' },
  { method: 'GET', path: '/api/finance/bias/*', purpose: 'list bias snapshots' },
  { method: 'GET', path: '/api/finance/timeline', purpose: 'timeline query with filters and paging' },
  { method: 'GET', path: '/api/finance/strategy-lab', purpose: 'baseline/candidate comparison and benchmark views' },
  { method: 'GET', path: '/api/finance/experiments', purpose: 'experiment center summary and recommendations' },
  { method: 'GET', path: '/api/finance/metrics', purpose: 'local observability metrics' },
  { method: 'POST', path: '/api/finance/replay/stu-effect/run', purpose: 'run active STU replay proof' },
  { method: 'GET', path: '/api/finance/replay/stu-effect', purpose: 'list replay proof entries' },
  { method: 'GET', path: '/api/finance/replay/query', purpose: 'replay-friendly linked query' },
  { method: 'GET', path: '/api/finance/replay/diagnostics', purpose: 'replay diagnostics summary' },
  { method: 'GET', path: '/api/finance/setup/status', purpose: 'setup status and admin view' },
  { method: 'POST', path: '/api/finance/setup/validate', purpose: 'validate setup wizard payload' },
  { method: 'POST', path: '/api/finance/setup/save-config', purpose: 'save setup config with secret protection' },
  { method: 'POST', path: '/api/finance/setup/bootstrap', purpose: 'initialize app resources from setup' },
  { method: 'POST', path: '/api/finance/setup/healthcheck', purpose: 'run setup health checks' },
  { method: 'POST', path: '/api/finance/setup/demo-run', purpose: 'enqueue and run setup demo task' },
  { method: 'GET', path: '/api/finance/settings/runtime', purpose: 'read runtime settings summary' },
  { method: 'POST', path: '/api/finance/settings/runtime/validate', purpose: 'validate runtime settings payload' },
  { method: 'POST', path: '/api/finance/settings/runtime/save', purpose: 'save runtime settings' },
  { method: 'POST', path: '/api/finance/settings/runtime/healthcheck', purpose: 'runtime healthcheck via router/gateway path' },
  { method: 'GET', path: '/api/finance/settings/runtime/history', purpose: 'runtime settings change history' },
  { method: 'POST', path: '/api/finance/settings/runtime/resolve-profile', purpose: 'resolve runtime profile/model alias' }
];
